### ISSUE TITLE
Build process for JS app

### ISSUE THREAD

**Issue by RaasAhsan** [PacketFire/paste-click#21]
In the current build, the `assets` directory (containing `/s` and `/up`) is served directly on NGINX without any preprocessing.

With the new JS app, there needs to be a preprocessing step where the Vue and JavaScript is compiled and optimized. The output is a directory with an `index.html` and the static JavaScript and CSS files.

We can route both `/s/` and `/up` to the same index.html since we'll use `vue-router` to inspect the browser URL.

When and where should this asset generation take place? Not sure if it lives inside the Dockerfile.

**Comment by ncatelli** [comment]
Per a side conversation, these assets are mounted into the openresty image in dev. We've decided to create a new image for openresty that inherits from the current image and handle the compilation within this image at container startup.

@RaasAhsan

**Comment by RaasAhsan** [comment]
Closed by #24 .
