### ISSUE TITLE
Shorter object IDs

### ISSUE THREAD

**Issue by RaasAhsan** [PacketFire/paste-click#34]
There has been several requests to have a shorter object ID instead of a long MD5 hash.

possible solutions:
- https://hashids.org/

**Comment by ncatelli** [comment]
I'm going to attempt to truncate the MD5s

**Comment by RaasAhsan** [comment]
Using MD5 hashes of the objects or a truncated form of it also gives us the opportunity to switch to random, shorter IDs in the future if we ever decide to.

**Comment by ncatelli** [comment]
After some discussion, we are going to go with Base62 encoding the checksum to bring it from 32 to 20 characters.
