### ISSUE TITLE
paste.click links not working

### ISSUE THREAD

**Issue by manufoy** [PacketFire/paste-click#61]
**Describe the bug**
All links on paste.click no longer function. This includes the links on the index page. The only thing that appears to function is plain text on the beta version of the site.

**To Reproduce**
* Visit any link on site

**Expected behavior**
I expect the site to work

**Screenshots**
<img width="942" alt="screen shot 2019-03-02 at 10 04 29 pm" src="https://user-images.githubusercontent.com/9674850/53683033-2f71e600-3d37-11e9-9a8a-3a88508e38ef.png">

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.3 (18D109)
 - Browser Ungoogled Chromium
 - Version 70.0.3538.110

**Comment by ncatelli** [comment]
Hello @manufoy and thank you for filing the issue,

This is known and we are working on updating the UI accordingly.

This is a duplicate, though more detailed, issue of #46. For the time being, we will the other issue and work off of this one.

**Comment by manufoy** [comment]
The "fix" doesn't address all links on the site. The links http://paste.click/s/TMtTCo#monokai does not resolve. In addition to the fact links in the old format posted to other places still don't resolve.

**Comment by ncatelli** [comment]
Looks like this example link was overlooked. One of us will update it accordingly soon. In regards to your other issue. This site was relaunched did and we expect many, if any, users yet. As such, no previous objects uploaded from the previous launch (those in the old six character) format will persist. We also make no guarantee that an object will persist indefinitely.
